/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlmanacRouteImport } from './routes/almanac'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PasswordRecoveryRouteImport } from './routes/password-recovery'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StoryRouteImport } from './routes/story'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdRevenueRouteImport } from './routes/admin.ad-revenue'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminBugsRouteImport } from './routes/admin.bugs'
import { Route as AdminGameRouteImport } from './routes/admin.game'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPartnershipsRouteImport } from './routes/admin.partnerships'
import { Route as AdminPlayerReportsRouteImport } from './routes/admin.player-reports'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as ApiMailRouteImport } from './routes/api/mail'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalAchievementsRouteImport } from './routes/portal.achievements'
import { Route as PortalAlmanacRouteImport } from './routes/portal.almanac'
import { Route as PortalFriendsRouteImport } from './routes/portal.friends'
import { Route as PortalInboxRouteImport } from './routes/portal.inbox'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalShopRouteImport } from './routes/portal.shop'
import { Route as AdminAdsIdRouteImport } from './routes/admin.ads.$id'
import { Route as ApiAdminAccountRouteImport } from './routes/api/admin/account'
import { Route as ApiAdminBugReportsRouteImport } from './routes/api/admin/bug-reports'
import { Route as ApiAdminDataRouteImport } from './routes/api/admin/data'
import { Route as ApiAdminPartnershipsRouteImport } from './routes/api/admin/partnerships'
import { Route as ApiAdminPaymongoOrdersRouteImport } from './routes/api/admin/paymongo-orders'
import { Route as ApiAdminPlayerReportsRouteImport } from './routes/api/admin/player-reports'
import { Route as ApiAdminPlayersRouteImport } from './routes/api/admin/players'
import { Route as ApiAdminSubmissionAttachmentsRouteImport } from './routes/api/admin/submission-attachments'
import { Route as ApiAuthCheckUsernameRouteImport } from './routes/api/auth/check-username'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthPlayerProfileRouteImport } from './routes/api/auth/player-profile'
import { Route as ApiAuthProfileRouteImport } from './routes/api/auth/profile'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiPaymongoCheckoutRouteImport } from './routes/api/paymongo/checkout'
import { Route as ApiPaymongoReturnRouteImport } from './routes/api/paymongo/return'
import { Route as ApiPaymongoStatusRouteImport } from './routes/api/paymongo/status'
import { Route as ApiPaymongoWebhookRouteImport } from './routes/api/paymongo/webhook'
import { Route as ApiPlayfabClientRouteImport } from './routes/api/playfab/client'
import { Route as ApiAuthPasswordRecoveryRequestRouteImport } from './routes/api/auth/password-recovery/request'
import { Route as ApiAuthPasswordRecoveryResetRouteImport } from './routes/api/auth/password-recovery/reset'
import { Route as ApiAuthPasswordRecoveryVerifyRouteImport } from './routes/api/auth/password-recovery/verify'
import { Route as ApiAuthPasswordChangeRouteImport } from './routes/api/auth/password/change'
import { Route as ApiAuthProfileSetupRouteImport } from './routes/api/auth/profile/setup'
import { Route as ApiPlayfabFriendsAddRouteImport } from './routes/api/playfab/friends/add'
import { Route as ApiPlayfabFriendsRemoveRouteImport } from './routes/api/playfab/friends/remove'
import { Route as ApiPlayfabPlayersSearchRouteImport } from './routes/api/playfab/players/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmanacRoute = AlmanacRouteImport.update({
  id: '/almanac',
  path: '/almanac',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRecoveryRoute = PasswordRecoveryRouteImport.update({
  id: '/password-recovery',
  path: '/password-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdRevenueRoute = AdminAdRevenueRouteImport.update({
  id: '/ad-revenue',
  path: '/ad-revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBugsRoute = AdminBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGameRoute = AdminGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnershipsRoute = AdminPartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayerReportsRoute = AdminPlayerReportsRouteImport.update({
  id: '/player-reports',
  path: '/player-reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailRoute = ApiMailRouteImport.update({
  id: '/api/mail',
  path: '/api/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAchievementsRoute = PortalAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAlmanacRoute = PortalAlmanacRouteImport.update({
  id: '/almanac',
  path: '/almanac',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFriendsRoute = PortalFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInboxRoute = PortalInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalShopRoute = PortalShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => PortalRoute,
} as any)
const AdminAdsIdRoute = AdminAdsIdRouteImport.update({
  id: '/ads/$id',
  path: '/ads/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminAccountRoute = ApiAdminAccountRouteImport.update({
  id: '/api/admin/account',
  path: '/api/admin/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBugReportsRoute = ApiAdminBugReportsRouteImport.update({
  id: '/api/admin/bug-reports',
  path: '/api/admin/bug-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDataRoute = ApiAdminDataRouteImport.update({
  id: '/api/admin/data',
  path: '/api/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPartnershipsRoute = ApiAdminPartnershipsRouteImport.update({
  id: '/api/admin/partnerships',
  path: '/api/admin/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPaymongoOrdersRoute = ApiAdminPaymongoOrdersRouteImport.update({
  id: '/api/admin/paymongo-orders',
  path: '/api/admin/paymongo-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPlayerReportsRoute = ApiAdminPlayerReportsRouteImport.update({
  id: '/api/admin/player-reports',
  path: '/api/admin/player-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPlayersRoute = ApiAdminPlayersRouteImport.update({
  id: '/api/admin/players',
  path: '/api/admin/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubmissionAttachmentsRoute =
  ApiAdminSubmissionAttachmentsRouteImport.update({
    id: '/api/admin/submission-attachments',
    path: '/api/admin/submission-attachments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthCheckUsernameRoute = ApiAuthCheckUsernameRouteImport.update({
  id: '/api/auth/check-username',
  path: '/api/auth/check-username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPlayerProfileRoute = ApiAuthPlayerProfileRouteImport.update({
  id: '/api/auth/player-profile',
  path: '/api/auth/player-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileRoute = ApiAuthProfileRouteImport.update({
  id: '/api/auth/profile',
  path: '/api/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymongoCheckoutRoute = ApiPaymongoCheckoutRouteImport.update({
  id: '/api/paymongo/checkout',
  path: '/api/paymongo/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymongoReturnRoute = ApiPaymongoReturnRouteImport.update({
  id: '/api/paymongo/return',
  path: '/api/paymongo/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymongoStatusRoute = ApiPaymongoStatusRouteImport.update({
  id: '/api/paymongo/status',
  path: '/api/paymongo/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymongoWebhookRoute = ApiPaymongoWebhookRouteImport.update({
  id: '/api/paymongo/webhook',
  path: '/api/paymongo/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayfabClientRoute = ApiPlayfabClientRouteImport.update({
  id: '/api/playfab/client',
  path: '/api/playfab/client',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasswordRecoveryRequestRoute =
  ApiAuthPasswordRecoveryRequestRouteImport.update({
    id: '/api/auth/password-recovery/request',
    path: '/api/auth/password-recovery/request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthPasswordRecoveryResetRoute =
  ApiAuthPasswordRecoveryResetRouteImport.update({
    id: '/api/auth/password-recovery/reset',
    path: '/api/auth/password-recovery/reset',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthPasswordRecoveryVerifyRoute =
  ApiAuthPasswordRecoveryVerifyRouteImport.update({
    id: '/api/auth/password-recovery/verify',
    path: '/api/auth/password-recovery/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthPasswordChangeRoute = ApiAuthPasswordChangeRouteImport.update({
  id: '/api/auth/password/change',
  path: '/api/auth/password/change',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileSetupRoute = ApiAuthProfileSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => ApiAuthProfileRoute,
} as any)
const ApiPlayfabFriendsAddRoute = ApiPlayfabFriendsAddRouteImport.update({
  id: '/api/playfab/friends/add',
  path: '/api/playfab/friends/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayfabFriendsRemoveRoute = ApiPlayfabFriendsRemoveRouteImport.update({
  id: '/api/playfab/friends/remove',
  path: '/api/playfab/friends/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayfabPlayersSearchRoute = ApiPlayfabPlayersSearchRouteImport.update({
  id: '/api/playfab/players/search',
  path: '/api/playfab/players/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/almanac': typeof AlmanacRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/password-recovery': typeof PasswordRecoveryRoute
  '/portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/story': typeof StoryRoute
  '/team': typeof TeamRoute
  '/admin/ad-revenue': typeof AdminAdRevenueRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/player-reports': typeof AdminPlayerReportsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/mail': typeof ApiMailRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/portal/achievements': typeof PortalAchievementsRoute
  '/portal/almanac': typeof PortalAlmanacRoute
  '/portal/friends': typeof PortalFriendsRoute
  '/portal/inbox': typeof PortalInboxRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/shop': typeof PortalShopRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/ads/$id': typeof AdminAdsIdRoute
  '/api/admin/account': typeof ApiAdminAccountRoute
  '/api/admin/bug-reports': typeof ApiAdminBugReportsRoute
  '/api/admin/data': typeof ApiAdminDataRoute
  '/api/admin/partnerships': typeof ApiAdminPartnershipsRoute
  '/api/admin/paymongo-orders': typeof ApiAdminPaymongoOrdersRoute
  '/api/admin/player-reports': typeof ApiAdminPlayerReportsRoute
  '/api/admin/players': typeof ApiAdminPlayersRoute
  '/api/admin/submission-attachments': typeof ApiAdminSubmissionAttachmentsRoute
  '/api/auth/check-username': typeof ApiAuthCheckUsernameRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/player-profile': typeof ApiAuthPlayerProfileRoute
  '/api/auth/profile': typeof ApiAuthProfileRouteWithChildren
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/paymongo/checkout': typeof ApiPaymongoCheckoutRoute
  '/api/paymongo/return': typeof ApiPaymongoReturnRoute
  '/api/paymongo/status': typeof ApiPaymongoStatusRoute
  '/api/paymongo/webhook': typeof ApiPaymongoWebhookRoute
  '/api/playfab/client': typeof ApiPlayfabClientRoute
  '/api/auth/password-recovery/request': typeof ApiAuthPasswordRecoveryRequestRoute
  '/api/auth/password-recovery/reset': typeof ApiAuthPasswordRecoveryResetRoute
  '/api/auth/password-recovery/verify': typeof ApiAuthPasswordRecoveryVerifyRoute
  '/api/auth/password/change': typeof ApiAuthPasswordChangeRoute
  '/api/auth/profile/setup': typeof ApiAuthProfileSetupRoute
  '/api/playfab/friends/add': typeof ApiPlayfabFriendsAddRoute
  '/api/playfab/friends/remove': typeof ApiPlayfabFriendsRemoveRoute
  '/api/playfab/players/search': typeof ApiPlayfabPlayersSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/almanac': typeof AlmanacRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/password-recovery': typeof PasswordRecoveryRoute
  '/signup': typeof SignupRoute
  '/story': typeof StoryRoute
  '/team': typeof TeamRoute
  '/admin/ad-revenue': typeof AdminAdRevenueRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/player-reports': typeof AdminPlayerReportsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/mail': typeof ApiMailRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/portal/achievements': typeof PortalAchievementsRoute
  '/portal/almanac': typeof PortalAlmanacRoute
  '/portal/friends': typeof PortalFriendsRoute
  '/portal/inbox': typeof PortalInboxRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/shop': typeof PortalShopRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/ads/$id': typeof AdminAdsIdRoute
  '/api/admin/account': typeof ApiAdminAccountRoute
  '/api/admin/bug-reports': typeof ApiAdminBugReportsRoute
  '/api/admin/data': typeof ApiAdminDataRoute
  '/api/admin/partnerships': typeof ApiAdminPartnershipsRoute
  '/api/admin/paymongo-orders': typeof ApiAdminPaymongoOrdersRoute
  '/api/admin/player-reports': typeof ApiAdminPlayerReportsRoute
  '/api/admin/players': typeof ApiAdminPlayersRoute
  '/api/admin/submission-attachments': typeof ApiAdminSubmissionAttachmentsRoute
  '/api/auth/check-username': typeof ApiAuthCheckUsernameRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/player-profile': typeof ApiAuthPlayerProfileRoute
  '/api/auth/profile': typeof ApiAuthProfileRouteWithChildren
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/paymongo/checkout': typeof ApiPaymongoCheckoutRoute
  '/api/paymongo/return': typeof ApiPaymongoReturnRoute
  '/api/paymongo/status': typeof ApiPaymongoStatusRoute
  '/api/paymongo/webhook': typeof ApiPaymongoWebhookRoute
  '/api/playfab/client': typeof ApiPlayfabClientRoute
  '/api/auth/password-recovery/request': typeof ApiAuthPasswordRecoveryRequestRoute
  '/api/auth/password-recovery/reset': typeof ApiAuthPasswordRecoveryResetRoute
  '/api/auth/password-recovery/verify': typeof ApiAuthPasswordRecoveryVerifyRoute
  '/api/auth/password/change': typeof ApiAuthPasswordChangeRoute
  '/api/auth/profile/setup': typeof ApiAuthProfileSetupRoute
  '/api/playfab/friends/add': typeof ApiPlayfabFriendsAddRoute
  '/api/playfab/friends/remove': typeof ApiPlayfabFriendsRemoveRoute
  '/api/playfab/players/search': typeof ApiPlayfabPlayersSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/almanac': typeof AlmanacRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/password-recovery': typeof PasswordRecoveryRoute
  '/portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/story': typeof StoryRoute
  '/team': typeof TeamRoute
  '/admin/ad-revenue': typeof AdminAdRevenueRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/player-reports': typeof AdminPlayerReportsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/api/mail': typeof ApiMailRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/portal/achievements': typeof PortalAchievementsRoute
  '/portal/almanac': typeof PortalAlmanacRoute
  '/portal/friends': typeof PortalFriendsRoute
  '/portal/inbox': typeof PortalInboxRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/shop': typeof PortalShopRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/ads/$id': typeof AdminAdsIdRoute
  '/api/admin/account': typeof ApiAdminAccountRoute
  '/api/admin/bug-reports': typeof ApiAdminBugReportsRoute
  '/api/admin/data': typeof ApiAdminDataRoute
  '/api/admin/partnerships': typeof ApiAdminPartnershipsRoute
  '/api/admin/paymongo-orders': typeof ApiAdminPaymongoOrdersRoute
  '/api/admin/player-reports': typeof ApiAdminPlayerReportsRoute
  '/api/admin/players': typeof ApiAdminPlayersRoute
  '/api/admin/submission-attachments': typeof ApiAdminSubmissionAttachmentsRoute
  '/api/auth/check-username': typeof ApiAuthCheckUsernameRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/player-profile': typeof ApiAuthPlayerProfileRoute
  '/api/auth/profile': typeof ApiAuthProfileRouteWithChildren
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/paymongo/checkout': typeof ApiPaymongoCheckoutRoute
  '/api/paymongo/return': typeof ApiPaymongoReturnRoute
  '/api/paymongo/status': typeof ApiPaymongoStatusRoute
  '/api/paymongo/webhook': typeof ApiPaymongoWebhookRoute
  '/api/playfab/client': typeof ApiPlayfabClientRoute
  '/api/auth/password-recovery/request': typeof ApiAuthPasswordRecoveryRequestRoute
  '/api/auth/password-recovery/reset': typeof ApiAuthPasswordRecoveryResetRoute
  '/api/auth/password-recovery/verify': typeof ApiAuthPasswordRecoveryVerifyRoute
  '/api/auth/password/change': typeof ApiAuthPasswordChangeRoute
  '/api/auth/profile/setup': typeof ApiAuthProfileSetupRoute
  '/api/playfab/friends/add': typeof ApiPlayfabFriendsAddRoute
  '/api/playfab/friends/remove': typeof ApiPlayfabFriendsRemoveRoute
  '/api/playfab/players/search': typeof ApiPlayfabPlayersSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/almanac'
    | '/contact'
    | '/download'
    | '/features'
    | '/login'
    | '/password-recovery'
    | '/portal'
    | '/signup'
    | '/story'
    | '/team'
    | '/admin/ad-revenue'
    | '/admin/analytics'
    | '/admin/bugs'
    | '/admin/game'
    | '/admin/notifications'
    | '/admin/partnerships'
    | '/admin/player-reports'
    | '/admin/players'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/login'
    | '/api/mail'
    | '/api/notifications'
    | '/portal/achievements'
    | '/portal/almanac'
    | '/portal/friends'
    | '/portal/inbox'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/shop'
    | '/admin/'
    | '/portal/'
    | '/admin/ads/$id'
    | '/api/admin/account'
    | '/api/admin/bug-reports'
    | '/api/admin/data'
    | '/api/admin/partnerships'
    | '/api/admin/paymongo-orders'
    | '/api/admin/player-reports'
    | '/api/admin/players'
    | '/api/admin/submission-attachments'
    | '/api/auth/check-username'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/player-profile'
    | '/api/auth/profile'
    | '/api/auth/register'
    | '/api/auth/session'
    | '/api/paymongo/checkout'
    | '/api/paymongo/return'
    | '/api/paymongo/status'
    | '/api/paymongo/webhook'
    | '/api/playfab/client'
    | '/api/auth/password-recovery/request'
    | '/api/auth/password-recovery/reset'
    | '/api/auth/password-recovery/verify'
    | '/api/auth/password/change'
    | '/api/auth/profile/setup'
    | '/api/playfab/friends/add'
    | '/api/playfab/friends/remove'
    | '/api/playfab/players/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/almanac'
    | '/contact'
    | '/download'
    | '/features'
    | '/login'
    | '/password-recovery'
    | '/signup'
    | '/story'
    | '/team'
    | '/admin/ad-revenue'
    | '/admin/analytics'
    | '/admin/bugs'
    | '/admin/game'
    | '/admin/notifications'
    | '/admin/partnerships'
    | '/admin/player-reports'
    | '/admin/players'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/login'
    | '/api/mail'
    | '/api/notifications'
    | '/portal/achievements'
    | '/portal/almanac'
    | '/portal/friends'
    | '/portal/inbox'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/shop'
    | '/admin'
    | '/portal'
    | '/admin/ads/$id'
    | '/api/admin/account'
    | '/api/admin/bug-reports'
    | '/api/admin/data'
    | '/api/admin/partnerships'
    | '/api/admin/paymongo-orders'
    | '/api/admin/player-reports'
    | '/api/admin/players'
    | '/api/admin/submission-attachments'
    | '/api/auth/check-username'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/player-profile'
    | '/api/auth/profile'
    | '/api/auth/register'
    | '/api/auth/session'
    | '/api/paymongo/checkout'
    | '/api/paymongo/return'
    | '/api/paymongo/status'
    | '/api/paymongo/webhook'
    | '/api/playfab/client'
    | '/api/auth/password-recovery/request'
    | '/api/auth/password-recovery/reset'
    | '/api/auth/password-recovery/verify'
    | '/api/auth/password/change'
    | '/api/auth/profile/setup'
    | '/api/playfab/friends/add'
    | '/api/playfab/friends/remove'
    | '/api/playfab/players/search'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/almanac'
    | '/contact'
    | '/download'
    | '/features'
    | '/login'
    | '/password-recovery'
    | '/portal'
    | '/signup'
    | '/story'
    | '/team'
    | '/admin/ad-revenue'
    | '/admin/analytics'
    | '/admin/bugs'
    | '/admin/game'
    | '/admin/notifications'
    | '/admin/partnerships'
    | '/admin/player-reports'
    | '/admin/players'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin_/login'
    | '/api/mail'
    | '/api/notifications'
    | '/portal/achievements'
    | '/portal/almanac'
    | '/portal/friends'
    | '/portal/inbox'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/shop'
    | '/admin/'
    | '/portal/'
    | '/admin/ads/$id'
    | '/api/admin/account'
    | '/api/admin/bug-reports'
    | '/api/admin/data'
    | '/api/admin/partnerships'
    | '/api/admin/paymongo-orders'
    | '/api/admin/player-reports'
    | '/api/admin/players'
    | '/api/admin/submission-attachments'
    | '/api/auth/check-username'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/player-profile'
    | '/api/auth/profile'
    | '/api/auth/register'
    | '/api/auth/session'
    | '/api/paymongo/checkout'
    | '/api/paymongo/return'
    | '/api/paymongo/status'
    | '/api/paymongo/webhook'
    | '/api/playfab/client'
    | '/api/auth/password-recovery/request'
    | '/api/auth/password-recovery/reset'
    | '/api/auth/password-recovery/verify'
    | '/api/auth/password/change'
    | '/api/auth/profile/setup'
    | '/api/playfab/friends/add'
    | '/api/playfab/friends/remove'
    | '/api/playfab/players/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlmanacRoute: typeof AlmanacRoute
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PasswordRecoveryRoute: typeof PasswordRecoveryRoute
  PortalRoute: typeof PortalRouteWithChildren
  SignupRoute: typeof SignupRoute
  StoryRoute: typeof StoryRoute
  TeamRoute: typeof TeamRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiMailRoute: typeof ApiMailRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiAdminAccountRoute: typeof ApiAdminAccountRoute
  ApiAdminBugReportsRoute: typeof ApiAdminBugReportsRoute
  ApiAdminDataRoute: typeof ApiAdminDataRoute
  ApiAdminPartnershipsRoute: typeof ApiAdminPartnershipsRoute
  ApiAdminPaymongoOrdersRoute: typeof ApiAdminPaymongoOrdersRoute
  ApiAdminPlayerReportsRoute: typeof ApiAdminPlayerReportsRoute
  ApiAdminPlayersRoute: typeof ApiAdminPlayersRoute
  ApiAdminSubmissionAttachmentsRoute: typeof ApiAdminSubmissionAttachmentsRoute
  ApiAuthCheckUsernameRoute: typeof ApiAuthCheckUsernameRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthPlayerProfileRoute: typeof ApiAuthPlayerProfileRoute
  ApiAuthProfileRoute: typeof ApiAuthProfileRouteWithChildren
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiPaymongoCheckoutRoute: typeof ApiPaymongoCheckoutRoute
  ApiPaymongoReturnRoute: typeof ApiPaymongoReturnRoute
  ApiPaymongoStatusRoute: typeof ApiPaymongoStatusRoute
  ApiPaymongoWebhookRoute: typeof ApiPaymongoWebhookRoute
  ApiPlayfabClientRoute: typeof ApiPlayfabClientRoute
  ApiAuthPasswordRecoveryRequestRoute: typeof ApiAuthPasswordRecoveryRequestRoute
  ApiAuthPasswordRecoveryResetRoute: typeof ApiAuthPasswordRecoveryResetRoute
  ApiAuthPasswordRecoveryVerifyRoute: typeof ApiAuthPasswordRecoveryVerifyRoute
  ApiAuthPasswordChangeRoute: typeof ApiAuthPasswordChangeRoute
  ApiPlayfabFriendsAddRoute: typeof ApiPlayfabFriendsAddRoute
  ApiPlayfabFriendsRemoveRoute: typeof ApiPlayfabFriendsRemoveRoute
  ApiPlayfabPlayersSearchRoute: typeof ApiPlayfabPlayersSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanac': {
      id: '/almanac'
      path: '/almanac'
      fullPath: '/almanac'
      preLoaderRoute: typeof AlmanacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-recovery': {
      id: '/password-recovery'
      path: '/password-recovery'
      fullPath: '/password-recovery'
      preLoaderRoute: typeof PasswordRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ad-revenue': {
      id: '/admin/ad-revenue'
      path: '/ad-revenue'
      fullPath: '/admin/ad-revenue'
      preLoaderRoute: typeof AdminAdRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bugs': {
      id: '/admin/bugs'
      path: '/bugs'
      fullPath: '/admin/bugs'
      preLoaderRoute: typeof AdminBugsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/game': {
      id: '/admin/game'
      path: '/game'
      fullPath: '/admin/game'
      preLoaderRoute: typeof AdminGameRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partnerships': {
      id: '/admin/partnerships'
      path: '/partnerships'
      fullPath: '/admin/partnerships'
      preLoaderRoute: typeof AdminPartnershipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/player-reports': {
      id: '/admin/player-reports'
      path: '/player-reports'
      fullPath: '/admin/player-reports'
      preLoaderRoute: typeof AdminPlayerReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail': {
      id: '/api/mail'
      path: '/api/mail'
      fullPath: '/api/mail'
      preLoaderRoute: typeof ApiMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/achievements': {
      id: '/portal/achievements'
      path: '/achievements'
      fullPath: '/portal/achievements'
      preLoaderRoute: typeof PortalAchievementsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/almanac': {
      id: '/portal/almanac'
      path: '/almanac'
      fullPath: '/portal/almanac'
      preLoaderRoute: typeof PortalAlmanacRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/friends': {
      id: '/portal/friends'
      path: '/friends'
      fullPath: '/portal/friends'
      preLoaderRoute: typeof PortalFriendsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/inbox': {
      id: '/portal/inbox'
      path: '/inbox'
      fullPath: '/portal/inbox'
      preLoaderRoute: typeof PortalInboxRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/shop': {
      id: '/portal/shop'
      path: '/shop'
      fullPath: '/portal/shop'
      preLoaderRoute: typeof PortalShopRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/ads/$id': {
      id: '/admin/ads/$id'
      path: '/ads/$id'
      fullPath: '/admin/ads/$id'
      preLoaderRoute: typeof AdminAdsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/account': {
      id: '/api/admin/account'
      path: '/api/admin/account'
      fullPath: '/api/admin/account'
      preLoaderRoute: typeof ApiAdminAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bug-reports': {
      id: '/api/admin/bug-reports'
      path: '/api/admin/bug-reports'
      fullPath: '/api/admin/bug-reports'
      preLoaderRoute: typeof ApiAdminBugReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/data': {
      id: '/api/admin/data'
      path: '/api/admin/data'
      fullPath: '/api/admin/data'
      preLoaderRoute: typeof ApiAdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/partnerships': {
      id: '/api/admin/partnerships'
      path: '/api/admin/partnerships'
      fullPath: '/api/admin/partnerships'
      preLoaderRoute: typeof ApiAdminPartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/paymongo-orders': {
      id: '/api/admin/paymongo-orders'
      path: '/api/admin/paymongo-orders'
      fullPath: '/api/admin/paymongo-orders'
      preLoaderRoute: typeof ApiAdminPaymongoOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/player-reports': {
      id: '/api/admin/player-reports'
      path: '/api/admin/player-reports'
      fullPath: '/api/admin/player-reports'
      preLoaderRoute: typeof ApiAdminPlayerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/players': {
      id: '/api/admin/players'
      path: '/api/admin/players'
      fullPath: '/api/admin/players'
      preLoaderRoute: typeof ApiAdminPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submission-attachments': {
      id: '/api/admin/submission-attachments'
      path: '/api/admin/submission-attachments'
      fullPath: '/api/admin/submission-attachments'
      preLoaderRoute: typeof ApiAdminSubmissionAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/check-username': {
      id: '/api/auth/check-username'
      path: '/api/auth/check-username'
      fullPath: '/api/auth/check-username'
      preLoaderRoute: typeof ApiAuthCheckUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/player-profile': {
      id: '/api/auth/player-profile'
      path: '/api/auth/player-profile'
      fullPath: '/api/auth/player-profile'
      preLoaderRoute: typeof ApiAuthPlayerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile': {
      id: '/api/auth/profile'
      path: '/api/auth/profile'
      fullPath: '/api/auth/profile'
      preLoaderRoute: typeof ApiAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paymongo/checkout': {
      id: '/api/paymongo/checkout'
      path: '/api/paymongo/checkout'
      fullPath: '/api/paymongo/checkout'
      preLoaderRoute: typeof ApiPaymongoCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paymongo/return': {
      id: '/api/paymongo/return'
      path: '/api/paymongo/return'
      fullPath: '/api/paymongo/return'
      preLoaderRoute: typeof ApiPaymongoReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paymongo/status': {
      id: '/api/paymongo/status'
      path: '/api/paymongo/status'
      fullPath: '/api/paymongo/status'
      preLoaderRoute: typeof ApiPaymongoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paymongo/webhook': {
      id: '/api/paymongo/webhook'
      path: '/api/paymongo/webhook'
      fullPath: '/api/paymongo/webhook'
      preLoaderRoute: typeof ApiPaymongoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playfab/client': {
      id: '/api/playfab/client'
      path: '/api/playfab/client'
      fullPath: '/api/playfab/client'
      preLoaderRoute: typeof ApiPlayfabClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/password-recovery/request': {
      id: '/api/auth/password-recovery/request'
      path: '/api/auth/password-recovery/request'
      fullPath: '/api/auth/password-recovery/request'
      preLoaderRoute: typeof ApiAuthPasswordRecoveryRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/password-recovery/reset': {
      id: '/api/auth/password-recovery/reset'
      path: '/api/auth/password-recovery/reset'
      fullPath: '/api/auth/password-recovery/reset'
      preLoaderRoute: typeof ApiAuthPasswordRecoveryResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/password-recovery/verify': {
      id: '/api/auth/password-recovery/verify'
      path: '/api/auth/password-recovery/verify'
      fullPath: '/api/auth/password-recovery/verify'
      preLoaderRoute: typeof ApiAuthPasswordRecoveryVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/password/change': {
      id: '/api/auth/password/change'
      path: '/api/auth/password/change'
      fullPath: '/api/auth/password/change'
      preLoaderRoute: typeof ApiAuthPasswordChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile/setup': {
      id: '/api/auth/profile/setup'
      path: '/setup'
      fullPath: '/api/auth/profile/setup'
      preLoaderRoute: typeof ApiAuthProfileSetupRouteImport
      parentRoute: typeof ApiAuthProfileRoute
    }
    '/api/playfab/friends/add': {
      id: '/api/playfab/friends/add'
      path: '/api/playfab/friends/add'
      fullPath: '/api/playfab/friends/add'
      preLoaderRoute: typeof ApiPlayfabFriendsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playfab/friends/remove': {
      id: '/api/playfab/friends/remove'
      path: '/api/playfab/friends/remove'
      fullPath: '/api/playfab/friends/remove'
      preLoaderRoute: typeof ApiPlayfabFriendsRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playfab/players/search': {
      id: '/api/playfab/players/search'
      path: '/api/playfab/players/search'
      fullPath: '/api/playfab/players/search'
      preLoaderRoute: typeof ApiPlayfabPlayersSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdRevenueRoute: typeof AdminAdRevenueRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBugsRoute: typeof AdminBugsRoute
  AdminGameRoute: typeof AdminGameRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPartnershipsRoute: typeof AdminPartnershipsRoute
  AdminPlayerReportsRoute: typeof AdminPlayerReportsRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdsIdRoute: typeof AdminAdsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdRevenueRoute: AdminAdRevenueRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBugsRoute: AdminBugsRoute,
  AdminGameRoute: AdminGameRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPartnershipsRoute: AdminPartnershipsRoute,
  AdminPlayerReportsRoute: AdminPlayerReportsRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAdsIdRoute: AdminAdsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalAchievementsRoute: typeof PortalAchievementsRoute
  PortalAlmanacRoute: typeof PortalAlmanacRoute
  PortalFriendsRoute: typeof PortalFriendsRoute
  PortalInboxRoute: typeof PortalInboxRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalShopRoute: typeof PortalShopRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAchievementsRoute: PortalAchievementsRoute,
  PortalAlmanacRoute: PortalAlmanacRoute,
  PortalFriendsRoute: PortalFriendsRoute,
  PortalInboxRoute: PortalInboxRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalShopRoute: PortalShopRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ApiAuthProfileRouteChildren {
  ApiAuthProfileSetupRoute: typeof ApiAuthProfileSetupRoute
}

const ApiAuthProfileRouteChildren: ApiAuthProfileRouteChildren = {
  ApiAuthProfileSetupRoute: ApiAuthProfileSetupRoute,
}

const ApiAuthProfileRouteWithChildren = ApiAuthProfileRoute._addFileChildren(
  ApiAuthProfileRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlmanacRoute: AlmanacRoute,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PasswordRecoveryRoute: PasswordRecoveryRoute,
  PortalRoute: PortalRouteWithChildren,
  SignupRoute: SignupRoute,
  StoryRoute: StoryRoute,
  TeamRoute: TeamRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiMailRoute: ApiMailRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiAdminAccountRoute: ApiAdminAccountRoute,
  ApiAdminBugReportsRoute: ApiAdminBugReportsRoute,
  ApiAdminDataRoute: ApiAdminDataRoute,
  ApiAdminPartnershipsRoute: ApiAdminPartnershipsRoute,
  ApiAdminPaymongoOrdersRoute: ApiAdminPaymongoOrdersRoute,
  ApiAdminPlayerReportsRoute: ApiAdminPlayerReportsRoute,
  ApiAdminPlayersRoute: ApiAdminPlayersRoute,
  ApiAdminSubmissionAttachmentsRoute: ApiAdminSubmissionAttachmentsRoute,
  ApiAuthCheckUsernameRoute: ApiAuthCheckUsernameRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthPlayerProfileRoute: ApiAuthPlayerProfileRoute,
  ApiAuthProfileRoute: ApiAuthProfileRouteWithChildren,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiPaymongoCheckoutRoute: ApiPaymongoCheckoutRoute,
  ApiPaymongoReturnRoute: ApiPaymongoReturnRoute,
  ApiPaymongoStatusRoute: ApiPaymongoStatusRoute,
  ApiPaymongoWebhookRoute: ApiPaymongoWebhookRoute,
  ApiPlayfabClientRoute: ApiPlayfabClientRoute,
  ApiAuthPasswordRecoveryRequestRoute: ApiAuthPasswordRecoveryRequestRoute,
  ApiAuthPasswordRecoveryResetRoute: ApiAuthPasswordRecoveryResetRoute,
  ApiAuthPasswordRecoveryVerifyRoute: ApiAuthPasswordRecoveryVerifyRoute,
  ApiAuthPasswordChangeRoute: ApiAuthPasswordChangeRoute,
  ApiPlayfabFriendsAddRoute: ApiPlayfabFriendsAddRoute,
  ApiPlayfabFriendsRemoveRoute: ApiPlayfabFriendsRemoveRoute,
  ApiPlayfabPlayersSearchRoute: ApiPlayfabPlayersSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
